<Workspace Version="1.3.0.875" X="-82" Y="-170" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="911cbb31-db8c-4a64-95dc-78949a9abaa6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="TextNote.ByLocation" x="985.5" y="450" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.TextNote.ByLocation@Revit.Elements.Views.View,Autodesk.DesignScript.Geometry.Point,string,string,Revit.Elements.TextNoteType,bool,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="True" />
      <PortInfo index="5" default="True" />
      <PortInfo index="6" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c95a289b-883e-4b05-ae95-cd6a8adac98e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.Current" x="393.5" y="333" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.Current" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3abe0d15-c550-412c-9770-a5fcf64de597" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.ActiveView" x="621.5" y="333" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.ActiveView">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e21d81a7-9669-4963-a267-f0206804c13f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="621.5" y="441" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <CoreNodeModels.Input.StringInput guid="32395fde-08f4-424d-bf57-9b2a7518cf7f" type="CoreNodeModels.Input.StringInput" nickname="String" x="621.5" y="549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>Just a test....</System.String>
      <System.String value="Just a test...." />
    </CoreNodeModels.Input.StringInput>
    <Archilab.Grimshaw.UI.HorizontalAlignmentStyleUI guid="623c1824-df01-48df-813c-39ac5cd78076" type="Archilab.Grimshaw.UI.HorizontalAlignmentStyleUI" nickname="Horizontal Alignment Style" x="621.5" y="633" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:Center" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c95a289b-883e-4b05-ae95-cd6a8adac98e" start_index="0" end="3abe0d15-c550-412c-9770-a5fcf64de597" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3abe0d15-c550-412c-9770-a5fcf64de597" start_index="0" end="911cbb31-db8c-4a64-95dc-78949a9abaa6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e21d81a7-9669-4963-a267-f0206804c13f" start_index="0" end="911cbb31-db8c-4a64-95dc-78949a9abaa6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="32395fde-08f4-424d-bf57-9b2a7518cf7f" start_index="0" end="911cbb31-db8c-4a64-95dc-78949a9abaa6" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="623c1824-df01-48df-813c-39ac5cd78076" start_index="0" end="911cbb31-db8c-4a64-95dc-78949a9abaa6" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Vista preliminar en segundo plano" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>